
import './globals.css'
import toast, {Toaster} from "react-hot-toast";

export const metadata = {
  title: 'Jonh Klein Services',
  description: 'Generated by create next  jomhapp',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
          
        
          <Toaster/>
            {children}
         

        </body>
    </html>
  )
}
